### ISSUE TITLE
RegexValidationValidator for search commands

### ISSUE THREAD

**Issue by glennblock** [splunk/splunk-sdk-python#116]
Currently search commands have the RegularExpression validator which checks whether or not the value is a valid regular expression. This is useful for enforcing that the value that is provide is a valid regex.

It would also be nice to have a validator which is initialized with a regex that it uses to validate the value. For example you can provide a regex for an SSN.

**Comment by David-Noble-at-work** [comment]
This feature is committed to the develop branch which contains a number of new features/bug fixes. See CHANGELOG.md for additional information.

**Comment by shakeelmohamed** [comment]
We've just released v1.5.0 to address this.

**Comment by glennblock** [comment]
Yup, I saw, I reported it :-)
