### ISSUE TITLE
Broken Link in `splunklib/searchcommands/search_command.py`

### ISSUE THREAD

**Issue by loganknecht** [splunk/splunk-sdk-python#139]
Line 1037 has a broken link. Not sure where it should be redirecting to.

**Comment by David-Noble-at-work** [comment]
I'll have a look at line 1037 when I've got access to a larger screen. Why do you not like the shortened URLs?

Sent from my iPhone

On Apr 6, 2016, at 6:19 PM, Logan Knecht <notifications@github.com<mailto:notifications@github.com>> wrote:


Line 1037 has a broken link. Not sure where it should be redirecting to.

**Comment by David-Noble-at-work** [comment]
Here’s a suitable replacement link: https://docs.python.org/2/library/__main__.html. It describes Python’s idiomatic “conditional script” stanza which causes a script to run:

if __name__ == "__main__":
    main()

The dispatch function makes use of this Python idiom. Can you include this link update in your pull request?

On Apr 6, 2016, at 6:26 PM, David Noble <dnoble@splunk.com<mailto:dnoble@splunk.com>> wrote:

I'll have a look at line 1037 when I've got access to a larger screen. Why do you not like the shortened URLs?

Sent from my iPhone

On Apr 6, 2016, at 6:19 PM, Logan Knecht <notifications@github.com<mailto:notifications@github.com>> wrote:


Line 1037 has a broken link. Not sure where it should be redirecting to.

**Comment by loganknecht** [comment]
@shakeelmohamed I believe this was merged into develop.

https://github.com/splunk/splunk-sdk-python/pull/140

**Comment by shakeelmohamed** [comment]
@loganknecht :+1:
