### ISSUE TITLE
Is maxinputs supported by SCP 2?

### ISSUE THREAD

**Issue by likel** [splunk/splunk-sdk-python#151]
When I specifies maxinputs=50000 in metadata returned to splunk. I got a warning 
`WARN  ChunkedExternProcessor - Unsupported metadata field sent by custom search command: maxinputs`

Seems SCP 1 supports maxinputs because I can find it in commands.conf.spec.

**Comment by shakeelmohamed** [comment]
@likel, It is not supported in SCPv2. The value of `maxresultrows` will be pulled from `limits.conf` by Splunkd.
