### ISSUE TITLE
Splunk-sdk-python Installation failed

### ISSUE THREAD

**Issue by sunnyanjani** [splunk/splunk-sdk-python#154]
While trying to install splunk-sdk-python ON Windows 7 64-bit. I have followed the approaches suggested in [http://dev.splunk.com/view/python-sdk/SP-CAAAEDG](url)
1. Using pip on windows.
Command used: `python.exe -m pip install splunk-sdk-python`
Error: print "Could not import coverage. Please install it and try again"
SyntaxError: Missing parentheses in call to 'print'.
2. Installing Python egg from pip.
Same error persists.
3. Cloning Splunk-sdk-python from git.
After downloading the zip from github and extracting it.
Running the command: `python setup.py` throws the same error.
![splunk-sdk-python error](https://cloud.githubusercontent.com/assets/6361547/17770804/4ee884c6-655d-11e6-8a2a-b81be50a1892.PNG)
Please help me in resolving the above issue.

**Comment by shakeelmohamed** [comment]
Hi @sunnyanjani,

The SDK is not compatible with Python 3, you'll need to install Python 2.7 in order to use it.
