### ISSUE TITLE
Instructions for running the test suite

### ISSUE THREAD

**Issue by boxed** [splunk/splunk-sdk-python#156]
The readme has some descriptions for running the test suite, but when I followed them with splunk lite many tests failed with what looked like failures because I needed the enterprise version... that's a guess obviously.

The travis file uses docker, but I didn't manage to get that working either. I got the image running but couldn't connect to it. Since I've never really worked with docker I don't know what I'm doing here.

(I was looking at helping out with a proper tox target and fixing python3 support via python-modernize but I'm giving up for the time being)

**Comment by shakeelmohamed** [comment]
Hi @boxed,

Splunk Light doesn't have support for the SDKs, so it's reasonable that many things won't work. You can see more about the feature differences on this [document](https://www.splunk.com/en_us/products/splunk-light/splunk-light-vs-splunk-enterprise.html).

There are detailed notes on running the tests in the [README](https://github.com/splunk/splunk-sdk-python#running-the-examples-and-unit-tests), did you need something else? The Travis CI config only uses Docker so we can start up a temporary Splunk instance during CI runs.

Please re-open this issue if you need something from us

**Comment by boxed** [comment]
You should mention which version of splunk you need to run the tests at least.
