### ISSUE TITLE
Documentation: Usage for each example script

### ISSUE THREAD

**Issue by sriramb12** [splunk/splunk-sdk-python#157]
It took some time for me to understand how to run a search with certain filters and output filters. 
A couple of examples should be embedded in --help option, to make life easier. Ex:

To pull alerts from a host for last 5 minutes:
./search.py "search sender_ip=<ip> earliest=-5m 
To pull alerts from a host for last 2 hours:
./search.py "search sender_ip=<ip> earliest=-2h

A few examples with different output formatting options also

**Comment by snickers2029** [comment]
This is more of a spl thing. Please refer to https://docs.splunk.com/Documentation/Splunk/7.0.2/SearchReference/UnderstandingSPLsyntax
