### ISSUE TITLE
Performance issue to delete/update an input

### ISSUE THREAD

**Issue by cheneysplunk** [splunk/splunk-sdk-python#168]
If I want to delete one data input, I have to list all of inputs, filter them out, and delete one. It has big performance impact when there are many data inputs in my Splunk ENV, even if I already know the data input type & name.

**Comment by snickers2029** [comment]
@cheneysplunk Created internal ticket DVPL-7289.

**Comment by shakeelmohamed** [comment]
@cheneysplunk hi, can you take a look at #247? This change should address your issue
