### ISSUE TITLE
Support Python 3!!! Don't cut us off! We pay you big money!

### ISSUE THREAD

**Issue by rhaarm** [splunk/splunk-sdk-python#186]
Since Issue #91 has been shutdown for comments, I'm creating a new issue. Please address the needs of those who keep bringing this up time and time again. Splunk is an "enterprise" product that we pay lots of money for and it's seem we keep getting the short end of the stick on this issue and no one at Splunk seems to care.

The many Open Source (not paid for) alternative eco-system supports both versions of Python and it seems a paid product can't get it's stuff together.

**Comment by shakeelmohamed** [comment]
Thank you for your support @rhaarm. The other thread was locked because the conversation was off-topic. Your concerns are valid, and have been heard.
Unfortunately my hands are tied for the reasons listed in #91.
I'm closing this issue as it's a duplicate.
