### ISSUE TITLE
Need to add a header to get past our load balancer when connecting to splunk host

### ISSUE THREAD

**Issue by DanEhrlich** [splunk/splunk-sdk-python#189]
There is a load balancer in front of the search heads for a splunk instance I am trying to connect to.
Is there a way to add a header that will always get sent when talking to the instance?

I do the following in curl and need an equivalent way using the Python SDK:

`curl -kv -H 'Magic-Header: <MY_MAGIC_TOKEN>' ...`

Any help would be appreciated.

**Comment by shakeelmohamed** [comment]
Hi @DanEhrlich,

You can define a custom handler method that sets your header. See the [handler example](https://github.com/splunk/splunk-sdk-python/blob/master/examples/handlers/handler_urllib2.py).
