### ISSUE TITLE
index_earliest parameter for search jobs not respected if search has sub-searches

### ISSUE THREAD

**Issue by spellanser** [splunk/splunk-sdk-python#199]
Hi! 
Then running basic search command (without sub-searches) with the only index_earliest provided everything works fine - search return results based on index_earliest parameter.
Then running the search with sub-searches and passing index_earliest parameter, for example:
`search index=main | append [search index=info ]` 
It ignores index_earliest and query all index events. 
I have tested this with every available search type from http://dev.splunk.com/view/python-sdk/SP-CAAAEE5

Also, the documentation is very poor, for example, how to query whole search result using normal search? It always return only 100 events, even if provide additional count parameter for search job.

**Comment by skylasam** [comment]
Tracking internally using https://jira.splunk.com/browse/DVPL-7355

**Comment by shakeelmohamed** [comment]
@spellanser can you share a code example to reproduce the issue?

**Comment by ncanumalla-splunk** [comment]
@spellanser Closing this issue due to no response on it. Please reopen if this is still an issue.
