### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by huangwenwenlili** [splunk/splunk-sdk-python#202]
connection.request("POST", "/services/auth/login", body, headers)
occur this error: 
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by shakeelmohamed** [comment]
Hi @huangwenwenlili, which versions of Python, the Python SDK, and Splunk are you using?

**Comment by mew1033** [comment]
You could just disable certificate verification: https://github.com/splunk/splunk-sdk-python/commit/5807d9076e708f21f3949fafea304485396b5d99

**Comment by skylasam** [comment]
@huangwenwenlili Are you still encountering this issue (even after disabling certificate validation) ? If so, please provide the information requested by @shakeelmohamed.

**Comment by dan1** [comment]
This should be resolved here https://github.com/splunk/splunk-sdk-python/pull/233

**Comment by dan1** [comment]
Should be resolved now.
