### ISSUE TITLE
Could you update the python3 support status on your website?

### ISSUE THREAD

**Issue by CodyKochmann** [splunk/splunk-sdk-python#226]
People were reporting that you didn't support python3 and finally sent me the following link that made them assume that python2 was the only supported version even though its going end of life next year.

[http://dev.splunk.com/view/python-sdk/SP-CAAAEFB#sdk](http://dev.splunk.com/view/python-sdk/SP-CAAAEFB#sdk)

![screen shot 2018-10-17 at 2 14 47 pm](https://user-images.githubusercontent.com/6968406/47107471-68417080-d217-11e8-8e38-a3827baa095d.png)

**Comment by shakeelmohamed** [comment]
Thanks @CodyKochmann , we've just updated the page. Take a look
