### ISSUE TITLE
Add support for licenser endpoint

### ISSUE THREAD

**Issue by DrakeW** [splunk/splunk-sdk-python#255]
The current `Service` class seems to be missing the `licenser/...` endpoints, it would be great if it can be added. 
In the meantime, is there a way to query any custom spulnkd endpoint that's not covered under the `Service` class with the SDK today?

**Comment by shakeelmohamed** [comment]
Hi @DrakeW, feel free to create a pull request to add any missing endpoints.
For reference, you can see the `b` example: https://github.com/splunk/splunk-sdk-python/blob/master/examples/abc/b.py

**Comment by ashah-splunk** [comment]
Hi @DrakeW , we hope the provided reference resolved the issue hence closing the issue. Please let us know if you still need help.
