### ISSUE TITLE
Support Bearer Token

### ISSUE THREAD

**Issue by nkadri-code** [splunk/splunk-sdk-python#260]
Splunk added the feature of creating and using Bearer Tokens for Rest API authentication.
https://docs.splunk.com/Documentation/Splunk/7.3.0/Security/UseAuthTokens

 Afaik, there is no possibility now to use Bearer token on the SDK

**Comment by shakeelmohamed** [comment]
Hey @nkadri-code, this is a newer feature added to Splunk Enterprise and we haven't scheduled this work yet for any of the Enterprise SDKs.

**Comment by omerl13** [comment]
Please review my PR #282

**Comment by akaila-splunk** [comment]
Hi @omerl13 , Thanks for PR  #282 . 
@nkadri-code since the PR by @omerl13 has been merged ,Python SDK supports authentication using bearer token.
Please use below code snippet for authenticating using bearer token,
```
import splunklib.client as client
service = client.connect(host='localhost',
                         splunkToken=<bearer-token>,
                         autologin=True)
```
