### ISSUE TITLE
README includes deprecated support process

### ISSUE THREAD

**Issue by halr9000** [splunk/splunk-sdk-python#298]
See https://github.com/splunk/splunk-sdk-python/blame/master/README.md#L289:

The email address "support@splunk.com" can no longer be used to open support cases. Instead, customers should login to the Support Portal using their Splunk.com account, and open a case that way. See: https://www.splunk.com/en_us/support-and-services.html and https://login.splunk.com/page/sso_redirect?type=portal

**Comment by ncanumalla-splunk** [comment]
The [current README](https://github.com/splunk/splunk-sdk-python#support) is up to date with these instructions. Closing as this is no longer an issue.
