### ISSUE TITLE
Generating command transform method is called multiple times

### ISSUE THREAD

**Issue by harsh8398** [splunk/splunk-sdk-python#326]
I looked at the slides here https://conf.splunk.com/files/2017/slides/extending-spl-with-custom-search-commands-and-the-splunk-sdk-for-python.pdf from which I got to know that the command is called multiple times before getting executed.

I see a similar issue #161 was resolved for generating command. Is there any solution to solve this for Eventing command as well?

The issue is that transform method is called multiple times before execute action is sent as metadata. This could cause duplicate log entries which can confuse the customer.

**Comment by vmalaviya-splunk** [comment]
Hey @harsh8398, We tried reproducing this issue by logging PID but we're getting just one entry in the console per one hit.
If it's possible could you please share the app you're trying to run?

**Comment by harsh8398** [comment]
@vmalaviya-splunk Thanks for looking into it. I also tried reproducing it today but it seems to be fixed now. Please feel free to close this issue.

**Comment by harsh8398** [comment]
@vmalaviya-splunk Thanks for looking into it. I also tried reproducing it today but it seems to be fixed now. I will close the issue now.
