### ISSUE TITLE
splunklib.client.Service request method documentation needs update

### ISSUE THREAD

**Issue by kacieh80** [splunk/splunk-sdk-python#328]
##### System Specs
splunk-sdk-python/1.6.11 (From binding.py)
Linux x86_64 x86_64 x86_64 GNU/Linux (AWS)
Python 2.7.15
Splunk version 7.3.4

##### Issue
The [`request()` method ](https://github.com/splunk/splunk-sdk-python/blob/master/splunklib/binding.py#L764 )of `splunklib.client.Service` needs updating. It says that you can send a `query` param into the method, but, you can not. This bubbles up to the [documentation](https://docs.splunk.com/DocumentationStatic/PythonSDK/1.6.11/client.html#splunklib.client.Service). If _not_ having `query` is intended, I can make the update, I have already applied to contribute.

**Comment by ashah-splunk** [comment]
@kacieh80 we have updated the documentation, would request you to have a look at the updated docs and let us know if it resolves the issue. Thanks!
