### ISSUE TITLE
Endpoint instance to HEC fails with 404 not found

### ISSUE THREAD

**Issue by dtrodger** [splunk/splunk-sdk-python#345]
Calls to this endpoint return a 404. The SDK appends a '/' to the end of any uri. So, /services/collector/event is found, /services/collector/event/ is not.

`event_collector_endpoint = splunklib.client.Endpoint(splunk_service, "/services/collector/event")`

Subclassing client.Endpoints and overriding init like below works.

<img width="622" alt="Screen Shot 2020-09-13 at 7 58 03 PM" src="https://user-images.githubusercontent.com/16841791/93033329-7367cb80-f5fb-11ea-9aa3-fd4ba697614e.png">

**Comment by ashah-splunk** [comment]
Hi @dtrodger , We have fixed the issue, and the changes will be available in the next release.
