### ISSUE TITLE
Import unexistant six.moves module

### ISSUE THREAD

**Issue by laconik** [splunk/splunk-sdk-python#349]
https://github.com/splunk/splunk-sdk-python/blob/7645d29b7fc1166c554bf9a7a03f40a02529ccc4/splunklib/__init__.py#L18

Causing ImportError developing modular inputs when using 

`from splunklib.modularinput import *`

**Comment by tdhellmann** [comment]
For the record: 
- are you using the latest SDK version (1.6.14)? 
- can you describe the steps you took to encounter this issue? Were you running an example, etc.

**Comment by tdhellmann** [comment]
Hey @laconik - we are not able to repro this on our end. It might be a consequence of how you are importing the mod inputs library. I'm going to close this for now, but please @ me if you are still encountering this issue and able to provide us with a set of repro steps.
