### ISSUE TITLE
Hostnames are ambiguously resolved on Dual Stack IPv4/6 Networks

### ISSUE THREAD

**Issue by andydoubleyou** [splunk/splunk-sdk-python#35]
Steps to reproduce:
Network like Splunk's, with support for both IPv4 and IPv6.
Two machines configured for both protocols.
One running Splunk.
One running Splunk Python SDK.

When hostname is provided, Splunk Python SDK will attempt to connect using IPv6 if the machine being reached has a AAAA record.  Unfortunately, Splunkd does not come configured automatically to listen on IPv6.  So the service attempts to connect and times out.  We should have a default of using IPv4 to connect, with a suite of configurable options akin to Splunk's own "connectUsingIpVersion" directive.

http://docs.splunk.com/Documentation/Splunk/latest/Admin/ConfigureSplunkforIPv6#Configure_Splunk_to_listen_on_an_IPv6_network

http://docs.python.org/library/socket.html

This is a common issue with any utility using php, perl, python... pretty much any language that utilizes the getHostByHostname family of underlying routines.  Sadly, this is not elegantly configurable as IPv6 support for python's socket is a compile time option.  Best work around is to use socket directly to resolve the hostname at connect time (do not cache this data) and use the appropriate returned IP address(es) for the connect option desired.

**Comment by itay** [comment]
Closing as we have no updated report here.
