### ISSUE TITLE
examplename.py is not present in the repository

### ISSUE THREAD

**Issue by amaljose01** [splunk/splunk-sdk-python#353]
examplename.py file is not present in the git repo based on the below documentation

Run the examples
Examples are located in the /splunk-sdk-python/examples directory. To run the examples at the command line, use the Python interpreter and include any arguments that are required by the example:

python examplename.py --username="admin" --password="changeme"
If you saved your login credentials in the .splunkrc file, you can omit those arguments:

python examplename.py
To get help for an example, use the --help argument with an example:

python examplename.py --help

**Comment by tdhellmann** [comment]
Which specific example were you trying to run?

**Comment by amaljose01** [comment]
I am not running anything specifically, the file examplename.py is not found in the repo provided as per the documentation

**Comment by ahvigil** [comment]
i think its implied that you replace `examplename.py` with the name of the example you'd like to run. Perhaps this can be made more explicit in the documentation.

**Comment by tdhellmann** [comment]
Right, there's not a specific example named "examplename.py", you have to replace "examplename" with the specific example in that directory that you want to run.

**Comment by amaljose01** [comment]
Thanks @tdhellmann  and @ahvigil , will do the same, it would be better if we could add an extra line in the documentation for the people trying out this for the first time

**Comment by ncanumalla-splunk** [comment]
Thanks for the feedback. Readme has been updated. Closing this issue.
