### ISSUE TITLE
Stale Alerts

### ISSUE THREAD

**Issue by rschuntigit** [splunk/splunk-sdk-python#368]
**Is your feature request related to a problem? Please describe.**
By using Splunk python SDK API, is there a way to find list of all Splunk alerts which have not been triggered for specified period of time? The basic idea is to run such report on regular basis and alert users on alerts which are just sitting there for specified period of time so that those alerts can be modified etc. Thanks

**Describe the solution you'd like**
Function that can return list of all saved searches which are not fired within specified window of time. For e.g. list of all alerts which are active but have not fired for last 2 months. 

**Describe alternatives you've considered**
I can get list of triggered alerts but this does not solves my purpose of finding stale alerts.

**Additional context**
This will help update/delete etc such alerts so that we can avoid alert fatigue.

**Comment by fantavlik** [comment]
Hi @rschuntigit it doesn't sound like this is a SDK-specific issue, for general questions about Splunk use cases [Splunk Community](https://community.splunk.com/) is probably the best place to ask.
