### ISSUE TITLE
SDK marked as Alpha

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-sdk-python#385]
https://github.com/splunk/splunk-sdk-python/blob/13f07cd08f8b2017c1cdafc2fbc75673013dc713/setup.py#L237

The current package is packaged and marked alpha but this is certainly release level at this point.

**Comment by ashah-splunk** [comment]
Hi @rfaircloth-splunk , thanks for bringing this to our attention. We have updated the Development Status for the SDK in the latest release 1.6.17. Hence closing this issue, please refer the latest SDK for the change.
