### ISSUE TITLE
`service.storage_passwords.list` misses space in `username` field

### ISSUE THREAD

**Issue by arys-splunk** [splunk/splunk-sdk-python#400]
**Describe the bug**
`service.storage_passwords.list` misses space in `username` field.

**To Reproduce**
1. Install https://splunkbase.splunk.com/app/2731/
2. Add 
```
[ test]
account_name = ucspe
account_password = ucspe
disable_ssl_verification = True
server_url = 10.141.36.107
```
to `local/splunk_ta_cisco_ucs_servers.conf`.
3. Go to Splunk, open Cisco UCS app and refresh the page.
4. Run this Python script
```python
from splunklib.client import connect

service = connect(username="admin", password="<your-admin-password>")


all_passwords = service.storage_passwords.list(count=-1, search="")

for p in all_passwords:
    print(p.state)
```
5. See that username field does not have space, but the stanza that we add in step 2 has.

**Expected behavior**
Username field should have space in it.

**Splunk (please complete the following information):**
- Version: 8.2.2.1
- OS: MacOS 11.6
- Deployment: single-instance

**SDK (please complete the following information):**
 - Version: 1.6.16
 - Language Runtime Version: Python 3.7
 - OS: MacOS 11.6

**Comment by akaila-splunk** [comment]
Hi @arys-splunk , We have fixed the issue, and the changes will be available in the next release.
PR for reference - #416

**Comment by ashah-splunk** [comment]
@arys-splunk please refer the latest python-sdk release 1.6.19, and please let us know if the issue still exists.
