### ISSUE TITLE
Doc: "Search Command Style Guide" link is dead

### ISSUE THREAD

**Issue by wcooley** [splunk/splunk-sdk-python#434]
https://github.com/splunk/splunk-sdk-python/blob/41ae2513e13715c4e860048201d99c5a1367a478/splunklib/searchcommands/__init__.py#L137

The link to the "Search Command Style Guide" is broken; it just redirects to dev.splunk.com. I don't see any obvious place where this page is now in the latest custom search command doc. I was able to dig up the last-known non-redirect content from the Wayback Machine: http://web.archive.org/web/20151207184958/http://docs.splunk.com/Documentation/Splunk/latest/Search/Searchcommandstyleguide

**Comment by ashah-splunk** [comment]
@wcooley we have updated the reference links for Custom Search Commands and the same is available in the latest SDK release.
