### ISSUE TITLE
JSONResultsReader does not work for Community Edition

### ISSUE THREAD

**Issue by marian-craciunescu** [splunk/splunk-sdk-python#457]
**Describe the bug**
I'm trying to get some result from a splunk server in python using JsonResultsReader, but the answer is not readable by json.
However using the old ResultsReader I'm able to retrieve it.
`Below is my code.

**To Reproduce**
````
 search_job = self.do_splunk_search(query_string, search_args)
        res = search_job.results(**{"count": total_size, "output_mode": "json"})
        final_res = []
        last_ts = None
        for result in results.JSONResultsReader(res):
            final_res.append(result)
        
````

**Expected behavior**
Call should return values .
However if i'm using  it returns values.
````
 for result in results.ResultsReader(search_job.results()):
                final_res.append(json.loads(json.dumps(result)))
````

**Logs or Screenshots**
If applicable, add logs or screenshots to help explain your problem.

**Splunk (please complete the following information):**
- Version: Splunk Enterprise Server 8.2.2
- OS:  Amazon AMI
- Deployment: single-instance

**SDK (please complete the following information):**
 - Version: [e.g. 1.6.19]
 - Language Runtime Version: [e.g. Python 3.9]
 - OS: [Linux]

**Comment by ashah-splunk** [comment]
Closing this Issue as the Events API is returning the required results.
