### ISSUE TITLE
Not able to run specific test when following instruction

### ISSUE THREAD

**Issue by hsekowski** [splunk/splunk-sdk-python#521]
**Describe the bug**
Not able to run specific test when following instruction

**To Reproduce**
1. Go to https://github.com/splunk/splunk-sdk-python/blob/master/README.md#run-the-unit-tests
2. Run `make specific_test_name`

**Expected behavior**
The README asks to run `make test_specific`
https://github.com/splunk/splunk-sdk-python/blob/master/scripts/test_specific.sh instead of "  tox -e py27,py37 [test_file_path]::[test_name]" instructs to run "tox -e py37 -- tests/test_file.py::TestClassName::test_method" (based on https://stackoverflow.com/questions/35697353/how-to-run-only-one-test-in-tox )

**Splunk (please complete the following information):**
- Version: [e.g. 9.0]
- OS: [e.g. MacOS 13.2.1; intel]

**SDK (please complete the following information):**
 - Version: [e.g. current]
 - Language Runtime Version: [e.g. Python 3.7]
- OS: [e.g. MacOS 13.2.1; intel]

**Comment by ncanumalla-splunk** [comment]
Thank you for catching this in the Readme and the contribution for the fix. @ashah-splunk Please take a look and validate this issue and associated PR.

**Comment by ashah-splunk** [comment]
test_specific.sh has been updated and corresponding PR is closed. Hence closing the issue. @hsekowski please let us know if you come across any other gaps or issues.
