### ISSUE TITLE
pycrypto package is deprecated (Python 3.11.4)

### ISSUE THREAD

**Issue by sonawanesarvesh** [splunk/splunk-sdk-python#537]
I am using Python version: Python 3.11.4

In which pycrypto package is deprecated but  i guess splunklib requires this package.
(I am getting error - Building wheel for pycrypto (pyproject.toml) did not run successfully.)

is there any solution or workaround for this issue?

**Comment by ashah-splunk** [comment]
Hi @sonawanesarvesh, are you getting the above error while executing `pip install splunk-sdk`?

**Comment by ashah-splunk** [comment]
Hi @harshcds1212, `splunklib` and `splunk-sdk` are different packages. We maintain the `splunk-sdk` package. Let us know if you face any issue while installing the `splunk-sdk` package.
