### ISSUE TITLE
splunklib.modularinput | <done/> written even when done=False

### ISSUE THREAD

**Issue by Jaykul** [splunk/splunk-sdk-python#88]
I promised myself I wouldn't gripe about how long it took us to figure out that there was a bug in the SDK and not in our code or in Splunk's handling of our input ....

Bottom line: in event.py line 103 you are checking if "done is not None" but you default it to "True" so we obviously set it to "False," (not "None") -- you should just be evaluating it for true.

**Comment by David-Noble-at-work** [comment]
I committed the change you suggested into branch bug/88 and verified that it did not break any modular input tests. Next step: add test coverage for this specific use case and merge into the develop branch.

Note that bug/88 is a branch of the develop branch that contains a number of new features/bug fixes. See CHANGELOG.md for additional information.

**Comment by shakeelmohamed** [comment]
Hi @Jaykul, we've just released v1.5.0 to address this. Thanks again for the bug report!
