### ISSUE TITLE
type property in outputs.conf is missing from Stanza.content

### ISSUE THREAD

**Issue by anotomoniz-r7** [splunk/splunk-sdk-python#92]
Attempting to retrieve the type parameter from a syslog stanza in outputs.conf using `service["outputs"]["foo"].content["type"]` fails. It turns out type collides with another value parsed form the atom feed result, which is also called type but denotes the entity's content type. Thus, each entity has a type field which looks something like `["tcp", "text/xml"]`. And before assigning Stanza.content, the type field is stripped out as "filtering some of the noise". All of this seems to indicate the problem is caused by a mixture of the property's name and a small bug in the Atom feed parser you're using.

The property is still accessible via a direct call to the REST API using `service.get("properties/outputs/foo/type")`, but its absence from the SDK is quite inconvenient.

**Comment by shakeelmohamed** [comment]
Just merged the fix to the develop branch, it will go out with the next release!

**Comment by shakeelmohamed** [comment]
Hi @anotomoniz-r7  we've just released v1.4.0 that addresses this.
