### ISSUE TITLE
issue while installing sdk

### ISSUE THREAD

**Issue by splunk47** [splunk/splunk-sdk-python#95]
File "setup.py", line 135
    with closing(tarfile.open(os.path.join("build", app + ".spl"), "w")) as spl:
               ^
SyntaxError: invalid syntax

kinldy help

**Comment by itay** [comment]
What version of Python are you using?

**Comment by splunk47** [comment]
I am doing testing where splunk 6.1 is installed so python comes with splunk is 2.7.5

**Comment by itay** [comment]
Can you share your full command line invocation?

**Comment by splunk47** [comment]
$SPLUNK_HOME/bin/python --version     this shows 2.7.5
for installing i am using this command 
python setup.py install
and in .bash_profile we have given the path like 
PYTHONPATH=/home/splunk/ET_Deployment/splunk-sdk-python

**Comment by itay** [comment]
So if you do:
```
$SPLUNK_HOME/bin/splunk cmd python setup.py install
```

Do you still get the error?

**Comment by splunk47** [comment]
[splunk@nllipidcn37110 splunk-sdk-python]$ $SPLUNK_HOME/bin/splunk cmd python setup.py install
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'install'

**Comment by itay** [comment]
If you do:

```
$SPLUNK_HOME/bin/splunk cmd python setup.py --help
```

what do you get?

**Comment by splunk47** [comment]
Common commands: (see '--help-commands' for more)

  setup.py build      will build the package underneath 'build/'
  setup.py install    will install the package

Global options:
  --verbose (-v)      run verbosely (default)
  --quiet (-q)        run quietly (turns verbosity off)
  --dry-run (-n)      don't actually do anything
  --help (-h)         show detailed help message
  --no-user-cfg       ignore pydistutils.cfg in your home directory
  --command-packages  list of packages that provide distutils commands

Information display options (just display information, ignore any commands)
  --help-commands     list all available commands
  --name              print package name
  --version (-V)      print package version
  --fullname          print <package name>-<version>
  --author            print the author's name
  --author-email      print the author's email address
  --maintainer        print the maintainer's name
  --maintainer-email  print the maintainer's email address
  --contact           print the maintainer's name if known, else the author's
  --contact-email     print the maintainer's email address if known, else the
                      author's
  --url               print the URL for this package
  --license           print the license of the package
  --licence           alias for --license
  --description       print the package description
  --long-description  print the long package description
  --platforms         print the list of platforms
  --classifiers       print the list of classifiers
  --keywords          print the list of keywords
  --provides          print the list of packages/modules provided
  --requires          print the list of packages/modules required
  --obsoletes         print the list of packages/modules made obsolete

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

**Comment by shakeelmohamed** [comment]
Hi @splunk47 sorry about the delay on this. I was able to help someone with this a couple of weeks ago.

If you want to install from the pypi remote servers:

```shell
sudo pip install --ignore-installed --target="$SPLUNK_HOME/lib/python2.7/site-packages" splunk-sdk
```

If you want to install from a local directory (ie: after a `git clone`):

```shell
sudo pip install --ignore-installed --target="$SPLUNK_HOME/lib/python2.7/site-packages" /an/absolute/path/to/splunk-sdk-python
```
