### ISSUE TITLE
Encrypted password while connecting to splunk

### ISSUE THREAD

**Issue by amith-reddy** [splunk/splunk-sdk-python#97]
Currently, I give password in a config file but it is visible to everyone. Is it possible to connect using encrypted password to splunk or using ssh keys? 

service = client.connect(
                host=host,
                port=port,
                username=userName,
                password=password)

**Comment by halr9000** [comment]
You can use Splunk to store your credentials. Here's an example: http://blogs.splunk.com/2011/03/15/storing-encrypted-credentials/

Alternately, you can handle it outside of Splunk using whatever Python method you like. Here are some ideas: http://stackoverflow.com/questions/7014953/i-need-to-securely-store-a-username-and-password-in-python-what-are-my-options

**Comment by shakeelmohamed** [comment]
Hi @amith-reddy, as @halr9000 pointed out there are some solutions for you. Can we close this?

**Comment by glennblock** [comment]
I think what is asking for is a way to use encrypted credentials to connect
to Splunk itself not just to store them in an encrypted fashion. Is that
correct @amith-reddy?

**Comment by itay** [comment]
No updates here - so closing.
